const state={token:localStorage.getItem('queuesmart_token'),user:JSON.parse(localStorage.getItem('queuesmart_user')||'null'),services:[],status:null};
const $=id=>document.getElementById(id);
function headers(){return state.token?{'Content-Type':'application/json','Authorization':`Bearer ${state.token}`}:{'Content-Type':'application/json'};}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}});let data=null;try{data=await response.json();}catch{data={detail:'Unexpected server response'};}if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function showMessage(text,error=false){const box=$('message');box.textContent=text;box.classList.remove('hidden','error');if(error)box.classList.add('error');window.setTimeout(()=>box.classList.add('hidden'),5000);}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const screen=$(id);if(screen)screen.classList.add('active');$('sidebar').classList.remove('open');loadScreen(id).catch(e=>showMessage(e.message,true));}
function updateNavigation(){document.querySelectorAll('.nav-user').forEach(x=>x.classList.toggle('hidden',state.user?.role!=='user'));document.querySelectorAll('.nav-admin').forEach(x=>x.classList.toggle('hidden',state.user?.role!=='administrator'));$('logoutButton').classList.toggle('hidden',!state.user);$('sessionLabel').textContent=state.user?`${state.user.full_name} (${state.user.role})`:'Not signed in';}
function saveSession(data){state.token=data.token;state.user=data.user;localStorage.setItem('queuesmart_token',state.token);localStorage.setItem('queuesmart_user',JSON.stringify(state.user));updateNavigation();}
function clearSession(){state.token=null;state.user=null;localStorage.removeItem('queuesmart_token');localStorage.removeItem('queuesmart_user');updateNavigation();showScreen('login');}
async function loadServices(){state.services=await api('/api/services');renderServiceOptions();return state.services;}
function renderServiceOptions(){const options=state.services.map(s=>`<option value="${s.id}">${s.name} (${s.queue_status})</option>`).join('');$('joinService').innerHTML='<option value="">Choose a service</option>'+options;$('adminQueueService').innerHTML=options;}
function serviceItem(s){return `<div class="list-item"><div><strong>${s.name}</strong><small>${s.waiting_count} waiting · ${s.expected_duration} min/service · ${s.priority_level} priority</small></div><span class="badge ${s.queue_status==='closed'?'closed':''}">${s.queue_status}</span></div>`;}
async function loadUserDashboard(){const [services,status,notes]=await Promise.all([loadServices(),api('/api/queues/status'),api('/api/notifications')]);state.status=status;$('dashPosition').textContent=status.active?`#${status.position}`:'-';$('dashService').textContent=status.active?status.service_name:'No active queue';$('dashWait').textContent=status.active?`${status.estimated_wait} min`:'0 min';$('dashNotificationCount').textContent=notes.filter(n=>n.status==='sent').length;$('dashboardServices').innerHTML=services.map(serviceItem).join('')||'<p>No services found.</p>';$('dashboardNotifications').innerHTML=notes.slice(0,5).map(n=>`<div class="list-item"><div><strong>${n.status==='viewed'?'Viewed':'New'}</strong><small>${n.message}</small></div></div>`).join('')||'<p>No notifications.</p>';}
async function updateEstimate(){const id=Number($('joinService').value);if(!id){$('joinEstimate').textContent='Select a service';$('queuePreview').innerHTML='<span>Choose an open service.</span>';return;}const estimate=await api(`/api/services/${id}/estimate`);$('joinEstimate').textContent=`${estimate.estimated_wait} minutes (position ${estimate.position})`;let boxes='';for(let i=1;i<=Math.min(estimate.position+2,10);i++){boxes+=`<span class="${i===estimate.position?'you':''}">${i===estimate.position?'You':i}</span>`;}$('queuePreview').innerHTML=boxes;}
async function loadQueueStatus(){const status=await api('/api/queues/status');state.status=status;$('statusService').textContent=status.active?status.service_name:'No active queue';$('statusTicketId').textContent=status.active?`#Q-${String(status.entry_id).padStart(3,'0')}`:'-';$('statusPosition').textContent=status.active?status.position:'-';$('statusWait').textContent=status.active?`${status.estimated_wait} min`:'-';$('statusState').textContent=status.active?status.status:'-';}
async function loadHistory(){const rows=await api('/api/history');$('historyBody').innerHTML=rows.map(r=>`<tr><td>${new Date(r.completed_at).toLocaleDateString()}</td><td>${r.service_name}</td><td>${r.wait_minutes} min</td><td><span class="badge ${r.outcome==='canceled'?'closed':''}">${r.outcome}</span></td></tr>`).join('')||'<tr><td colspan="4">No history records yet.</td></tr>';}
async function loadAdminDashboard(){const data=await api('/api/admin/dashboard');state.services=data.services;renderServiceOptions();$('adminOpen').textContent=data.open_queues;$('adminWaiting').textContent=data.total_waiting;$('adminLongest').textContent=`${data.longest_estimated_wait} min`;$('adminServiceSummary').innerHTML=data.services.map(s=>`<div class="service-card"><strong>${s.name}</strong><small>${s.waiting_count} waiting · ${s.queue_status}</small><button class="secondary" onclick="toggleQueue(${s.id})">${s.queue_status==='open'?'Close':'Open'} Queue</button></div>`).join('');}
async function loadServiceManagement(){const services=await loadServices();$('serviceList').innerHTML=services.map(serviceItem).join('');}
async function loadAdminQueue(){const serviceId=Number($('adminQueueService').value);if(!serviceId)return;const data=await api(`/api/admin/queues/${serviceId}`);$('adminQueueEntries').innerHTML=data.entries.map(e=>`<div class="queue-entry"><div><strong>#${e.position} ${e.full_name}</strong><small>${e.reason_for_visit} · ${e.email}</small></div><div><button class="link-button" onclick="moveEntry(${e.entry_id},${Math.max(1,e.position-1)})">Move Up</button><button class="link-button" onclick="removeEntry(${e.entry_id})">Remove</button></div></div>`).join('')||'<p>No users are waiting.</p>';$('adminActivity').textContent=`${data.entries.length} waiting in ${data.service_name}. Queue is ${data.status}.`;}
async function loadScreen(id){if(id==='user-dashboard')await loadUserDashboard();if(id==='join-queue'){await loadServices();await updateEstimate();}if(id==='queue-status')await loadQueueStatus();if(id==='history')await loadHistory();if(id==='admin-dashboard')await loadAdminDashboard();if(id==='service-management')await loadServiceManagement();if(id==='queue-management'){await loadServices();await loadAdminQueue();}}
window.toggleQueue=async id=>{try{await api(`/api/services/${id}/queue/toggle`,{method:'POST'});showMessage('Queue status updated.');await loadAdminDashboard();}catch(e){showMessage(e.message,true);}};
window.moveEntry=async(id,position)=>{try{await api(`/api/admin/queue-entries/${id}/move`,{method:'POST',body:JSON.stringify({position})});showMessage('Queue position updated.');await loadAdminQueue();}catch(e){showMessage(e.message,true);}};
window.removeEntry=async id=>{try{await api(`/api/admin/queue-entries/${id}`,{method:'DELETE'});showMessage('Queue entry removed.');await loadAdminQueue();}catch(e){showMessage(e.message,true);}};
document.querySelectorAll('[data-screen]').forEach(button=>button.addEventListener('click',()=>showScreen(button.dataset.screen)));
$('menuButton').addEventListener('click',()=>$('sidebar').classList.toggle('open'));
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{const data=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});saveSession(data);showMessage('Login successful.');showScreen(data.user.role==='administrator'?'admin-dashboard':'user-dashboard');}catch(err){showMessage(err.message,true);}});
$('registerForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/auth/register',{method:'POST',body:JSON.stringify({full_name:$('registerName').value,email:$('registerEmail').value,password:$('registerPassword').value,role:$('registerRole').value,contact_info:$('registerContact').value||null,preferences:null})});showMessage('Account created. You can now log in.');showScreen('login');}catch(err){showMessage(err.message,true);}});
$('logoutButton').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch{}clearSession();});
$('joinService').addEventListener('change',()=>updateEstimate().catch(e=>showMessage(e.message,true)));
$('joinForm').addEventListener('submit',async e=>{e.preventDefault();try{const result=await api('/api/queues/join',{method:'POST',body:JSON.stringify({service_id:Number($('joinService').value),reason_for_visit:$('joinReason').value})});showMessage(`Joined ${result.service_name} at position ${result.position}.`);showScreen('queue-status');}catch(err){showMessage(err.message,true);}});
$('leaveQueueButton').addEventListener('click',async()=>{try{const status=await api('/api/queues/status');if(!status.active)throw new Error('You are not currently waiting in a queue.');await api(`/api/queues/${status.queue_id}/leave`,{method:'DELETE'});showMessage('You left the queue.');await updateEstimate();}catch(err){showMessage(err.message,true);}});
$('serviceForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/services',{method:'POST',body:JSON.stringify({name:$('serviceName').value,description:$('serviceDescription').value,expected_duration:Number($('serviceDuration').value),priority_level:$('servicePriority').value})});e.target.reset();showMessage('Service saved to the database.');await loadServiceManagement();}catch(err){showMessage(err.message,true);}});
$('adminQueueService').addEventListener('change',()=>loadAdminQueue().catch(e=>showMessage(e.message,true)));
$('serveNextButton').addEventListener('click',async()=>{try{const id=Number($('adminQueueService').value);await api(`/api/admin/queues/${id}/serve-next`,{method:'POST'});showMessage('Next user served and history updated.');await loadAdminQueue();}catch(err){showMessage(err.message,true);}});
updateNavigation();if(state.user&&state.token)showScreen(state.user.role==='administrator'?'admin-dashboard':'user-dashboard');
